// <auto-generated />
namespace Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class expose_authoredbyid_inmodel : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(expose_authoredbyid_inmodel));
        
        string IMigrationMetadata.Id
        {
            get { return "202112101240119_expose_authoredbyid_inmodel"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
