// <auto-generated />
namespace Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class added_rating_to_book : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(added_rating_to_book));
        
        string IMigrationMetadata.Id
        {
            get { return "202112151343518_added_rating_to_book"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
